apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webportal-v4-admin-microservice
    app.kubernetes.io/component: webportal-v4-admin-microservice
    app.kubernetes.io/instance: webportal-v4-admin-microservice
  name: webportal-v4-admin-microservice
  namespace: dev-old-dmb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: webportal-v4-admin-microservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: webportal-v4-admin-microservice_load_cm
      labels:
        deployment: webportal-v4-admin-microservice
    spec:
      containers:
      - image: <PATCH_ME>
        imagePullPolicy: IfNotPresent
        name: webportal-v4-admin-microservice
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        envFrom:
          - configMapRef:
              name: webportal-v4-admin-microservice-cm
          - secretRef:
              name: webportal-v4-admin-microservice-secret
      imagePullSecrets:
      - name: private-docker-registry
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
