apiVersion: v1
kind: Service
metadata:
  labels:
    app: webportal-v4-admin-microservice
    app.kubernetes.io/component: webportal-v4-admin-microservice
    app.kubernetes.io/instance: webportal-v4-admin-microservice
  name: webportal-v4-admin-microservice
  
spec:
  ports:
  - port: 8080
  selector:
    deployment: webportal-v4-admin-microservice
