apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-api-int
    # app.kubernetes.io/component: demo-api-int
    # app.kubernetes.io/instance: demo-api-int
  name: demo-api-int
  
spec:
  ports:
  - port: 8080
  selector:
    deployment: demo-api-int
